### ISSUE TITLE
Support Generics for FeedItemRepository

### ISSUE THREAD

**Issue by steffenmalisi** [rest-feeds/restfeed-server-java#1]
FeedItemRepository currently returns a FeedItem.

This means that you have to use the FeedItem class in all your layers, starting from repositories up to your controllers.

To have more flexibility for different needs - which may include for example separating (domain) classes from DTOs in your controllers, using frameworks like Spring Data which uses annotations etc etc. - I would suggest to support generics for the FeedItemRepository.

```
public interface FeedItemRepository<T> {
  List<T> findByFeedPositionGreaterThanEqual(String feed, long position, int limit);
}
```

There could be a default version which supports the current implementation for users without special needs.

PR follows to make a suggestion.

**Comment by jochenchrist** [comment]
Thanks for your suggestion. I will have a look this weekend.

**Comment by jochenchrist** [comment]
I am not fully convinced, that `FeedItemRepository` should return domain classes. In terms of DDD, this repository is rather infrastructure level. The mapping should be done within the application.

Also, for simplicity I'd rather prefer to not add the default classes and mappers.

Maybe it would help me to understand your specific needs.

**Comment by jochenchrist** [comment]
I can see that the `FeedItem` class may be too limited and might be needed to be extended.

In a more simplified version, with
```
FeedItemRepository<T extends FeedItem>
```

(the generic type still extends `FeedItem`)

Please have a look at MR #3 and share your thoughts if this may be sufficient for your need.s

**Comment by steffenmalisi** [comment]
> I am not fully convinced, that `FeedItemRepository` should return domain classes. In terms of DDD, this repository is rather infrastructure level. The mapping should be done within the application.
> 
> Also, for simplicity I'd rather prefer to not add the default classes and mappers.
> 
> Maybe it would help me to understand your specific needs.

Hi @jochenchrist, thanks for your reply.

`FeedItemRepository` is just the interface, which could be in the domain layer. The implementation of that interface would be infrastructure level, right. If the inferface would not return domain objects, your domain layer would have to know infrastructure details (in this case infrastructure classes) and thus would not be independet of technical details like it should.

That decribes in a way my use case. We use Spring Data at the infrastructure layer, map our entities to domain objects within the infrastructure layer and map them again into DTOs in the api layer. It is important for me to have full flexibility in the infrastructure layer and not to use the same class through multiple layers. This is not given by using `FeedItem` with its specific fields. It's totally right to have a contract like `FeedItem`in the api layer for communication between client and server. But how this contract is fulfilled should not be tied too hard to specifications of the lib. Therefore I suggested to use a mapper to have this flexibility and also get your contract fulfilled. Hopefully this could lead to a broader usage of that lib.

I would have no problem with dropping the default classes. This is nothing I would need, but I thought it could be useful for existing users.

**Comment by jochenchrist** [comment]
I will come with an update next week.

**Comment by jochenchrist** [comment]
I decided to support Generics for the data attribute in `FeedItem`.

With `Object`, it is still possible to use any type as feed entry for mixed feed types.

In terms of DDD, the actual `FeedItem` class should not be used or mapped to a domain class, as the feed is part of the infrastructure.
